/* Local browser checks with catalog fixtures. No paid model or auth calls. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createRequire } from 'node:module';
import { loadTS } from './helpers.mjs';
const { chromium } = createRequire(import.meta.url)('playwright');
const { PLAYERS, COUNTRIES } = loadTS('src/lib/players.ts');
const models = PLAYERS.map(player => ({ id: player.id, name: player.name, contextLength: 200000, promptPrice: .000001, completionPrice: .000002 }));
const baseURL = process.env.TEST_BASE_URL || 'http://127.0.0.1:3001';
const output = process.env.TEST_OUTPUT_DIR || '/tmp/letsdebate-player-qa';
fs.mkdirSync(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let catalogMode = 'ok';
  await page.route('**/api/models', route => catalogMode === 'error'
    ? route.fulfill({ status: 502, json: { error: '테스트용 카탈로그 오류' } })
    : route.fulfill({ json: { models: catalogMode === 'partial' ? models.slice(0, 14) : models } }));
  await page.route('**/api/auth/session', route => route.fulfill({ json: { configured: false, user: null } }));
  await page.route('**/api/tournament/match', () => { throw new Error('Unexpected paid match request'); });
  const visit = async path => { await page.goto(baseURL + path); };
  const card = index => page.locator('.scouting-card').filter({ has: page.getByRole('heading', { name: PLAYERS[index].name, exact: true }) });
  const select = index => card(index).getByRole('button').click();
  await visit('/characters');
  await page.waitForFunction(() => document.querySelectorAll('.scouting-actions button:enabled').length === 15);
  const names = () => page.locator('.scouting-identity h3').allTextContents();
  const chooseSort = async label => {
    await page.getByRole('button', { name: /^선수 정렬:/ }).click();
    await page.getByRole('group', { name: '정렬 기준' }).getByRole('button', { name: label, exact: true }).click();
  };
  await chooseSort('이름순');
  const alphabetical = [...PLAYERS].sort((a, b) => a.name.localeCompare(b.name, 'ko', { numeric: true, sensitivity: 'base' }));
  assert.deepEqual(await names(), alphabetical.map(player => player.name));
  await page.locator('.player-country-filters button').filter({ hasText: '미국' }).click();
  assert.deepEqual(await names(), alphabetical.filter(player => player.country === 'US').map(player => player.name));
  await page.locator('.player-country-filters button').filter({ hasText: '전체' }).click();
  await chooseSort('국가순');
  const countries = await page.locator('.scouting-card-top .player-country').allTextContents();
  assert.deepEqual(countries, [...PLAYERS].sort((a, b) => COUNTRIES[a.country].name.localeCompare(COUNTRIES[b.country].name, 'ko')).map(player => `${COUNTRIES[player.country].flag} ${COUNTRIES[player.country].name}`));
  await chooseSort('추천순');
  assert.deepEqual(await names(), [0, 2, 3, 4, 7, 9, 13, 1, 5, 6, 8, 10, 11, 12, 14].map(index => PLAYERS[index].name));
  await page.getByRole('button', { name: /^선수 정렬:/ }).click();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('group', { name: '정렬 기준' }).count(), 0);
  assert.equal(await page.locator('.player-radar').count(), 15);
  assert.equal(await page.locator('.radar-fill').count(), 12, 'twelve sourced intelligence indices create closed polygons');
  for (const width of [320, 390, 600, 768, 1112, 1440]) {
    await page.setViewportSize({ width, height: 1050 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, `gallery overflow at ${width}`);
  }
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({ path: `${output}/desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${output}/mobile.png` });
  await card(0).screenshot({ path: `${output}/card.png` });
  await page.getByRole('button', { name: '능력치 보는 법' }).click();
  await page.getByRole('dialog').waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.locator('.player-country-filters button').filter({ hasText: '한국' }).click();
  assert.equal(await page.locator('.scouting-card').count(), 1);
  await select(7);
  await page.locator('.player-country-filters button').filter({ hasText: '일본' }).click();
  await select(14);
  await page.locator('.player-country-filters button').filter({ hasText: '전체' }).click();
  await page.getByLabel('AI 선수 검색').fill('스파크');
  assert.equal(await page.locator('.scouting-card').count(), 1);
  await select(3);
  await page.getByLabel('AI 선수 검색').fill('no-such-player');
  await page.getByRole('heading', { name: '찾는 선수가 없어요' }).waitFor();
  await page.getByRole('button', { name: '전체 선수 보기' }).click();
  await select(0);
  await page.getByRole('button', { name: '이 선수들로 배틀 만들기' }).click();
  await page.waitForURL('**/tournament/new?players=*');
  await page.waitForFunction(() => document.querySelectorAll('.lineup-slot.filled').length === 4);
  assert.deepEqual(await page.locator('.lineup-slot.filled strong').allTextContents(), [models[7].name, models[14].name, models[3].name, models[0].name]);
  assert.equal(await page.locator('.model-option').count(), 15);
  await page.getByRole('button', { name: '심판 선택', exact: true }).click();
  assert.equal(await page.getByRole('dialog').locator('.model-option').count(), 15);
  await page.getByRole('dialog').locator('.model-option').filter({ hasText: models[1].name }).click();
  await page.getByLabel('토론 주제', { exact: true }).fill('AI 모델의 토론으로 새로운 관점을 얻을 수 있을까?');
  await page.getByRole('button', { name: '대진표 만들기', exact: true }).click();
  await page.waitForURL('**/tournament?id=*');
  assert.equal(await page.locator('.bracket-match').count(), 3);
  await visit('/characters');
  await page.waitForFunction(() => document.querySelectorAll('.scouting-actions button:enabled').length === 15);
  for (let index = 0; index < 8; index++) await select(index);
  assert.equal(await card(8).getByRole('button').isDisabled(), true);
  await select(0);
  await select(14);
  await page.getByRole('button', { name: '이 선수들로 배틀 만들기' }).click();
  await page.waitForURL('**/tournament/new?players=*');
  await page.waitForFunction(() => document.querySelectorAll('.lineup-slot.filled').length === 8);
  assert.equal(await page.getByRole('button', { name: /8강 토너먼트/ }).getAttribute('aria-pressed'), 'true');
  catalogMode = 'partial';
  await visit(`/tournament/new?${new URLSearchParams({players: `${models[0].id},${models[14].id}`})}`);
  await page.getByRole('status').filter({ hasText: '일부 선수가' }).waitFor();
  assert.equal(await page.locator('.lineup-slot.filled').count(), 1);
  await visit('/characters');
  await page.waitForFunction(() => document.querySelectorAll('.scouting-actions button:enabled').length === 14);
  assert.equal(await card(14).getByRole('button').isDisabled(), true);
  catalogMode = 'error';
  await visit('/characters');
  await page.getByRole('alert').filter({ hasText: '테스트용 카탈로그 오류' }).waitFor();
  assert.equal(await page.locator('.scouting-actions button:enabled').count(), 0);
  catalogMode = 'ok';
  await page.getByRole('button', { name: '선수 목록 다시 확인' }).click();
  await page.waitForFunction(() => document.querySelectorAll('.scouting-actions button:enabled').length === 15);
  assert.deepEqual(errors, []);
  console.log('PASS: 15 cards, metrics, responsive widths, country/search, 4/8 draft carryover, judge, bracket, unavailable catalog, error/retry');
} finally { await browser.close(); }
